name: BoneHurtingJuice
version: @plugin_version@
main: io.github.cultofclang.bonehurtingjuice.BoneHurtPlugin
api-version: 1.15
depend:
  - mckotlinlibs
commands:
  boneinfo:
               description: Why are my bones hurting?
               usage: /boneinfo