name: BoneHurtingJuice
version: ${plugin_version}
main: org.cultofclang.bonehurtingjuice.BoneHurtPlugin
api-version: 1.17
commands:
  boneinfo:
       description: Why are my bones hurting?
       usage: /boneinfo
